using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class GrabSync {
    [RealtimeProperty(1, true, true)]
    private int _grabNumber;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class GrabSync : RealtimeModel {
    public int grabNumber {
        get {
            return _grabNumberProperty.value;
        }
        set {
            if (_grabNumberProperty.value == value) return;
            _grabNumberProperty.value = value;
            InvalidateReliableLength();
            FireGrabNumberDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(GrabSync model, T value);
    public event PropertyChangedHandler<int> grabNumberDidChange;
    
    public enum PropertyID : uint {
        GrabNumber = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _grabNumberProperty;
    
    #endregion
    
    public GrabSync() : base(null) {
        _grabNumberProperty = new ReliableProperty<int>(1, _grabNumber);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _grabNumberProperty.UnsubscribeCallback();
    }
    
    private void FireGrabNumberDidChange(int value) {
        try {
            grabNumberDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _grabNumberProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _grabNumberProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.GrabNumber: {
                    changed = _grabNumberProperty.Read(stream, context);
                    if (changed) FireGrabNumberDidChange(grabNumber);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _grabNumber = grabNumber;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
